backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/img
media_library:
  name: cloudinary
  config:
    cloud_name: dq104qc4m
    api_key: 717158453188245
    multiple: true
public_folder: /img
publish_mode: editorial_workflow

collections:
  - name: "products"
    label: "Products"
    folder: "src/pages/products"
    create: true
    slug: "{{prod_id}}"
    fields:
      - {
          label: "Template Key",
          name: "template",
          widget: "hidden",
          default: "product",
        }
      - {
          label: "Title",
          name: "title",
          widget: "hidden",
          default: "{{prod_id}}",
        }
      - {
          label: "Product ID",
          name: "prod_id",
          widget: "products",
          separator: __,
        }
      - {
          label: "Leather color",
          name: "leather_color",
          widget: "color",
          allowInput: "true",
          required: false,
        }
      - {
          label: "Thread color",
          name: "thread_color",
          widget: "color",
          allowInput: "true",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }
      - {
          label: "Images",
          name: "featuredimage",
          widget: "image",
          media_library: { name: "cloudinary", allow_multiple: true },
        }
